### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by guojize** [Eafoo/eatcat#3]
您好，我非常喜欢您的改版，并觉得它很有练习价值。我希望您能够在游戏内增加一些键型，这样或许能帮到更多的人。

具体而言，我希望增加以下键型：

> 生成在上个键对侧的键（例如上个键是1或2则随机生成3和4，另一侧同理）

非常感谢您对这个项目的付出。如您能采纳，我将不胜感激。

**Comment by Eafoo** [comment]
好的~非常好的提议！感谢~

**Comment by Eafoo** [comment]
好的！非常好的提议呢！感谢！！！

**Comment by Eafoo** [comment]
更新了！您可以再去看看新的帮助文档（还是点那个蓝字）！
