### ISSUE TITLE
部分电脑浏览器下按键缺失

### ISSUE THREAD

**Issue by MuYing-wSakura** [Eafoo/eatcat#5]
如题。
部分PC浏览器（例如edge）下可能是因为缩放问题？
会导致部分按键在显示范围之外，且页面无法滚动，导致部分按键无法被选择

**Comment by MuYing-wSakura** [comment]
具体例子：
![mmexport1643536867258](https://user-images.githubusercontent.com/62366679/151695177-4891f971-45db-41ca-ba30-5722b9fd9c46.png)
![mmexport1643536865618](https://user-images.githubusercontent.com/62366679/151695195-fc5bf41d-0490-45d8-b32b-7679e5e87e2c.png)

**Comment by Eafoo** [comment]
把界面缩小一下就可以了

**Comment by MuYing-wSakura** [comment]
> 把界面缩小一下就可以了

edge确实可以改，但是目前不知道别的浏览器有没有类似问题

**Comment by Eafoo** [comment]
主流浏览器应该都可以缩放界面的，不需要担心这个呢
